# Generated by Django 4.2.3 on 2023-07-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_relatorio', models.CharField(max_length=100, verbose_name='Nome do relatório')),
                ('desc_relatorio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do relatório')),
                ('link_relatorio', models.URLField(verbose_name='Url do relatório')),
                ('img_relatorio', models.ImageField(blank=True, null=True, upload_to='media_relatorio', verbose_name='Foto')),
                ('filial_relatorio', models.CharField(max_length=100, verbose_name='Filial Relatório')),
            ],
        ),
    ]
